"""empty message

Revision ID: 2c50ce077a5c
Revises: 883f3bb58f23
Create Date: 2019-06-14 09:00:23.237633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c50ce077a5c'
down_revision = '883f3bb58f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etuid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['etuid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etuid')

    # ### end Alembic commands ###
