"""empty message

Revision ID: 2da83f3e1a8a
Revises: 461c540266d1
Create Date: 2019-03-09 13:25:45.713427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da83f3e1a8a'
down_revision = '461c540266d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_element', sa.Column('food_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_element', 'food_name')
    # ### end Alembic commands ###
