"""empty message

Revision ID: 2f86d350067d
Revises: 79b932374ddd
Create Date: 2019-06-19 11:02:11.270095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f86d350067d'
down_revision = '79b932374ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseelement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ename', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseelement', schema=None) as batch_op:
        batch_op.drop_column('ename')

    # ### end Alembic commands ###
