"""empty message

Revision ID: 3d6e4d3ea208
Revises: 2f86d350067d
Create Date: 2019-06-19 11:06:36.613411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6e4d3ea208'
down_revision = '2f86d350067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseelement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mealid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('meid', 'meal', ['mealid'], ['mid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseelement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mealid')

    # ### end Alembic commands ###
