"""empty message

Revision ID: 461c540266d1
Revises: 90d763e029fe
Create Date: 2019-03-08 13:08:47.731749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461c540266d1'
down_revision = '90d763e029fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtype', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodtype', 'calories')
    # ### end Alembic commands ###
