"""empty message

Revision ID: 4753e5542b0d
Revises: 94623cc8e293
Create Date: 2019-06-24 10:52:01.545302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4753e5542b0d'
down_revision = '94623cc8e293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeoffset', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('timeoffset')

    # ### end Alembic commands ###
