"""empty message

Revision ID: 63aec1ea985f
Revises: ce9d46ee303e
Create Date: 2019-04-08 12:55:27.170687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aec1ea985f'
down_revision = 'ce9d46ee303e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodelement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodelement', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
