"""empty message

Revision ID: 7f35904a9097
Revises: 33ef28090bb4
Create Date: 2019-06-14 08:51:42.754666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f35904a9097'
down_revision = '33ef28090bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
