"""empty message

Revision ID: 883f3bb58f23
Revises: 16c3377fc866
Create Date: 2019-06-14 08:56:37.956294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883f3bb58f23'
down_revision = '16c3377fc866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etuid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['etuid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etuid')

    # ### end Alembic commands ###
