"""empty message

Revision ID: 90d763e029fe
Revises: 9301793747ea
Create Date: 2019-03-08 13:00:44.097190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d763e029fe'
down_revision = '9301793747ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_element', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('food_element', sa.Column('carb_amt', sa.Integer(), nullable=True))
    op.add_column('food_element', sa.Column('fat_amt', sa.Integer(), nullable=True))
    op.add_column('food_element', sa.Column('protein_amt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_element', 'protein_amt')
    op.drop_column('food_element', 'fat_amt')
    op.drop_column('food_element', 'carb_amt')
    op.drop_column('food_element', 'calories')
    # ### end Alembic commands ###
