"""empty message

Revision ID: 9301793747ea
Revises: abe6b898a269
Create Date: 2019-02-23 11:55:27.384485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9301793747ea'
down_revision = 'abe6b898a269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_element', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_element', 'color')
    # ### end Alembic commands ###
