"""empty message

Revision ID: 9750e85a73e5
Revises: a7f2521a43e8
Create Date: 2019-03-31 11:33:38.982188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9750e85a73e5'
down_revision = 'a7f2521a43e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('mealid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mealid'], ['meal.mid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('mealid', 'userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    # ### end Alembic commands ###
