"""empty message

Revision ID: 998a9bc53e03
Revises: d572704d3f81
Create Date: 2019-06-10 10:29:22.381449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a9bc53e03'
down_revision = 'd572704d3f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posttags')
    op.drop_table('post')
    op.drop_table('tag')
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('details')

    op.create_table('tag',
    sa.Column('tid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('post',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=300), nullable=True),
    sa.Column('uid', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.username'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('posttags',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('tid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['post.pid'], ),
    sa.ForeignKeyConstraint(['tid'], ['tag.tid'], ),
    sa.PrimaryKeyConstraint('pid', 'tid')
    )
    # ### end Alembic commands ###
