"""empty message

Revision ID: a7f2521a43e8
Revises: 
Create Date: 2019-03-31 11:21:39.358505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f2521a43e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('foodtype',
    sa.Column('ftid', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('serv_name', sa.String(length=64), nullable=True),
    sa.Column('protein_amt', sa.Integer(), nullable=True),
    sa.Column('carb_amt', sa.Integer(), nullable=True),
    sa.Column('fat_amt', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('ftid')
    )
    op.create_table('foodelement',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Float(), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('carb_amt', sa.Integer(), nullable=True),
    sa.Column('protein_amt', sa.Integer(), nullable=True),
    sa.Column('fat_amt', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('previous_changes', sa.Boolean(), nullable=True),
    sa.Column('mealid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['foodtype.ftid'], ),
    sa.ForeignKeyConstraint(['mealid'], ['meal.mid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.username'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foodelement')
    op.drop_table('foodtype')
    op.drop_table('user')
    op.drop_table('meal')
    # ### end Alembic commands ###
