"""empty message

Revision ID: abe6b898a269
Revises: 782b0fa3d3c6
Create Date: 2019-02-22 10:25:40.547324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe6b898a269'
down_revision = '782b0fa3d3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtype', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodtype', 'color')
    # ### end Alembic commands ###
