"""empty message

Revision ID: cb366fb58de1
Revises: 8594b73ac54b
Create Date: 2019-06-22 11:42:28.739409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb366fb58de1'
down_revision = '8594b73ac54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weightelement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weightid', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('wid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weightelement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wid', sa.FLOAT(), nullable=False))
        batch_op.drop_column('weightid')

    # ### end Alembic commands ###
