"""empty message

Revision ID: d778d6dacf12
Revises: 
Create Date: 2019-02-05 11:38:47.373290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd778d6dacf12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodtype',
    sa.Column('ftid', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('serv_name', sa.String(length=64), nullable=True),
    sa.Column('protein_amt', sa.Integer(), nullable=True),
    sa.Column('carb_amt', sa.Integer(), nullable=True),
    sa.Column('fat_amt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ftid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('food_types', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('food_element',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Float(), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['foodtype.ftid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_element')
    op.drop_table('user')
    op.drop_table('foodtype')
    # ### end Alembic commands ###
