"""empty message

Revision ID: f3629067b7fc
Revises: 0034307147c9
Create Date: 2019-06-14 09:08:53.839238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3629067b7fc'
down_revision = '0034307147c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['etid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etid')

    # ### end Alembic commands ###
