"""empty message

Revision ID: f85a7a43ad7a
Revises: 63aec1ea985f
Create Date: 2019-04-27 09:39:22.601299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85a7a43ad7a'
down_revision = '63aec1ea985f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercisetype',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('mets', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('tag',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('calorietarget',
    sa.Column('ctid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('dtstarted', sa.String(length=40), nullable=True),
    sa.Column('dtended', sa.String(length=40), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.username'], ),
    sa.PrimaryKeyConstraint('ctid')
    )
    op.create_table('exerciseelement',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('ts_created', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('etid', sa.Integer(), nullable=True),
    sa.Column('calsburned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etid'], ['exercisetype.tid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_table('follows',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('post',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.username'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('weightelement',
    sa.Column('wid', sa.Float(), nullable=False),
    sa.Column('ts_created', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('val', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.username'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weightelement')
    op.drop_table('post')
    op.drop_table('follows')
    op.drop_table('exerciseelement')
    op.drop_table('calorietarget')
    op.drop_table('tag')
    op.drop_table('exercisetype')
    # ### end Alembic commands ###
