"""empty message

Revision ID: fd713f6e45cb
Revises: 2c50ce077a5c
Create Date: 2019-06-14 09:02:22.395825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd713f6e45cb'
down_revision = '2c50ce077a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etuid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['etuid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercisetype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etuid')

    # ### end Alembic commands ###
